# syntax=docker/dockerfile:1.7

ARG BASE_IMAGE=cross-pi
FROM ${BASE_IMAGE} AS builder

WORKDIR /src

COPY . /src

RUN --mount=type=cache,target=/build,sharing=locked \
	--mount=type=cache,target=/root/.cache/ccache,sharing=locked \
	cmake \
	-S /src \
	-B /build \
	-G Ninja \
	-DCMAKE_TOOLCHAIN_FILE="$CROSS_TOOLCHAIN" \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/install \
	-DCMAKE_C_COMPILER_LAUNCHER=ccache \
	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
	&& cmake --build /build --parallel \
	&& rm -rf /install \
	&& cmake --install /build

FROM scratch AS artifact

COPY --from=builder /install /install